### ISSUE TITLE
Fullscreen feature not working

### ISSUE THREAD

**Issue by rokumatsumoto** [justinribeiro/stl-part-viewer#2]
@justinribeiro thanks for the web component.

## Expected Behavior

Model should be displayed on fullscreen when fullscreen button clicked.

Triggered with this code on console.
`$( "stl-part-viewer" ).__enterFullscreen()`  

![skull full screen](https://user-images.githubusercontent.com/28678254/56424766-4dc97c00-62ba-11e9-8520-eea6392f75f1.png)

## Current Behavior

Nothing happens on console and visual when i clicked fullscreen button.

![skull](https://user-images.githubusercontent.com/28678254/56425235-0643ef80-62bc-11e9-85e8-d0b3a92f5b93.png)

## Possible Solution

- 
## Steps to Reproduce

https://github.com/rokumatsumoto/boyutluseyler
I'm using your component on this project.

1. yarn add @justinribeiro/stl-part-viewer
1. [Import](https://github.com/rokumatsumoto/boyutluseyler/blob/92f16a11c3992ad40ad222ea2039d17b82a3df52/app/javascript/packs/application.js#L40) 
1. [Use](https://github.com/rokumatsumoto/boyutluseyler/blob/92f16a11c3992ad40ad222ea2039d17b82a3df52/app/views/pages/home.html.haml#L3)
1. Tried on latest chrome, firefox, opera, safari and mobile safari (10.3.3) 

## Context (Environment)

`node -v`
v11.14.0

`yarn -v`
1.15.2

`rails -v`
Rails 5.2.2.1

`gem list | grep webpacker`
[webpacker](https://github.com/rails/webpacker) (4.0.2)

[Webpack environment.js file](https://github.com/rokumatsumoto/boyutluseyler/blob/b792f0b4c9ee3ddf65a1be384411ffef6c091f0e/config/webpack/environment.js)

[Webpacker.yml file](https://github.com/rokumatsumoto/boyutluseyler/blob/b792f0b4c9ee3ddf65a1be384411ffef6c091f0e/config/webpacker.yml)

[package.json file](https://github.com/rokumatsumoto/boyutluseyler/blob/master/package.json)

**system info**
![system](https://user-images.githubusercontent.com/28678254/56425964-0b566e00-62bf-11e9-955e-a133dfacb02f.png)

## Detailed Description

-
## Possible Implementation

-

**Comment by justinribeiro** [comment]
Thanks for the report! I'll take a look and see what's going on.

**Comment by rokumatsumoto** [comment]
@justinribeiro thanks, now it's working modern desktop browsers, but could not make it work on mobile safari (10, 12)
